### ISSUE TITLE
Frontend Testing

### ISSUE THREAD

**Issue by akocerke** [akocerke/FilmSerienempfehlungen#168]

**Comment by techmocker** [comment]
Wenn man nur FIlme als Favoriten hat wird der Header "Serien" auch angezeigt und umgekehrt.

Evtl eine info drunter als H6? "Füge weitere Serien/Filme hinzu um Sie hier zu sehen"

**Comment by akocerke** [comment]
machen wir noch eine schöne Lösung if else etc um evtl die nicht vorhandenen Benutzer Favoriten SERIE/FILME Überschrift ausblenden ;)
