### ISSUE TITLE
Recherche API tmdb implementieren

### ISSUE THREAD

**Issue by akocerke** [akocerke/FilmSerienempfehlungen#28]
Funktionsweise
Doku der API
Postman Abfragen

**Comment by techmocker** [comment]
import axios from 'axios';

const options = {
    method: 'GET',
    url: 'https://api.themoviedb.org/3/authentication',
    headers: {
      accept: 'application/json',
      Authorization: 'Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxYWQzOTdmODViNmZlOTA5MTVlY2I5MmUxNWMwYTNjYyIsInN1YiI6IjY2MTU0MjBhMDQ4NjM4MDE0OTE5ZTljNiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.iq-_hqLOmZ0wXup07L7IQ8kfYi0lwytGma1pR09SqAM'
    }
  };
  
  axios
    .request(options)
    .then(function (response) {
      console.log(response.data);
    })
    .catch(function (error) {
      console.error(error);
    });

**Comment by akocerke** [comment]
erledigt
